[package]
name = "generated"
version = "0.1.0"
edition.workspace = true

[dependencies]
core-db = { workspace = true }
core-datatable = { workspace = true }
core-i18n = { workspace = true }
core-web = { workspace = true }
core-jobs = { workspace = true }
core-notify = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
schemars = { workspace = true }
validator = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
db-gen = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
